# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoWidget(object):
    def setupUi(self, InfoWidget):
        InfoWidget.setObjectName("InfoWidget")
        InfoWidget.resize(285, 366)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bestSolutionMatrixLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.bestSolutionMatrixLabel.setObjectName("bestSolutionMatrixLabel")
        self.verticalLayout.addWidget(self.bestSolutionMatrixLabel)
        self.matrixWidget = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.matrixWidget.setEnabled(True)
        self.matrixWidget.setAutoFillBackground(False)
        self.matrixWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.matrixWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.matrixWidget.setTabKeyNavigation(True)
        self.matrixWidget.setAlternatingRowColors(False)
        self.matrixWidget.setShowGrid(True)
        self.matrixWidget.setRowCount(5)
        self.matrixWidget.setColumnCount(5)
        self.matrixWidget.setObjectName("matrixWidget")
        self.matrixWidget.horizontalHeader().setVisible(False)
        self.matrixWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.matrixWidget.horizontalHeader().setDefaultSectionSize(45)
        self.matrixWidget.horizontalHeader().setMinimumSectionSize(30)
        self.matrixWidget.verticalHeader().setVisible(False)
        self.matrixWidget.verticalHeader().setCascadingSectionResizes(True)
        self.matrixWidget.verticalHeader().setSortIndicatorShown(False)
        self.matrixWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.matrixWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bestSolutionCost = QtWidgets.QLabel(self.dockWidgetContents)
        self.bestSolutionCost.setObjectName("bestSolutionCost")
        self.horizontalLayout_4.addWidget(self.bestSolutionCost)
        self.bestSolCost = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.bestSolCost.setEnabled(False)
        self.bestSolCost.setObjectName("bestSolCost")
        self.horizontalLayout_4.addWidget(self.bestSolCost)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.averageGenerationCost = QtWidgets.QLabel(self.dockWidgetContents)
        self.averageGenerationCost.setObjectName("averageGenerationCost")
        self.horizontalLayout_9.addWidget(self.averageGenerationCost)
        self.averageGenCost = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.averageGenCost.setEnabled(False)
        self.averageGenCost.setObjectName("averageGenCost")
        self.horizontalLayout_9.addWidget(self.averageGenCost)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        InfoWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(InfoWidget)
        QtCore.QMetaObject.connectSlotsByName(InfoWidget)

    def retranslateUi(self, InfoWidget):
        _translate = QtCore.QCoreApplication.translate
        InfoWidget.setWindowTitle(_translate("InfoWidget", "InfoWidget"))
        self.bestSolutionMatrixLabel.setText(_translate("InfoWidget", "Best solution:"))
        self.matrixWidget.setSortingEnabled(False)
        self.bestSolutionCost.setText(_translate("InfoWidget", "Best solution cost:"))
        self.averageGenerationCost.setText(_translate("InfoWidget", "Average gen. cost:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InfoWidget = QtWidgets.QDockWidget()
    ui = Ui_InfoWidget()
    ui.setupUi(InfoWidget)
    InfoWidget.show()
    sys.exit(app.exec_())
